### PR TITLE
Switch to using KaTeX to render math formulae

### PR DESCRIPTION
**Pull request by FiveYellowMice**
I've noticed the math functionality has been removed due to #10 . I understand that is a genuine concern, but this capability was critical for my usage. So I tried to make it work with KaTeX so it renders locally.

Since the fonts used by KaTeX are relatively large, I removed the `dist` folder from the repo altogether.

### CODE REVIEW

**Comment by mobitar** [comment]
Not sure that I understand this PR..it seems to revert a lot of changes made as part of the removal of LaTeX. This includes [server side components](https://github.com/sn-extensions/math-editor/pull/11/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR12) and lower versions in the package.json for many packages?

**Comment by FiveYellowMice** [comment]
I just reverted 0b7d145864f4bf682c2ba7d46a3a95f83b554a2c first then I could work upon the old LaTeX rendering code. The `dns-prefetch` and `preconnect` was there before the functionality removal, and it's my overlook to not remove it again. As for the lower versions in `package.json`, all I did in that file was just reverting it and add the KaTeX package, should I have used the post- 0b7d145864f4bf682c2ba7d46a3a95f83b554a2c `package.json` instead?

**Comment by mobitar** [comment]
I can't merge this PR in its current state. You have to build on top of what we have now, not go back in time and build on top of that. It's really hard to understand the changes being made here, and I can't spend a lot of time reviewing this, so it has to be very self-evident what's happening.

**Comment by FiveYellowMice** [comment]
Okay, is this better?

**Comment by mobitar** [comment]
Much better 👌

**Pull request merged**
